# rootfs.tar.gz和kernel与n1打包脚本制作镜像

name: part-packit-img-2024

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      openwrt_armvirt:
        description: '下载openwrt*rootfs.tar.gz的url'
        required: true
        default: https://github.com/sswdr/openwrt-actions/releases/download/backup.2024.01.01_build.2024.02.28.16.33/openwrt-armvirt-64-generic-rootfs.tar.gz
      kernel_version_name:
        description: '内核版本'
        required: true
        default: 5.15.145

env:
  openwrt_armvirt: ${{ github.event.inputs.openwrt_armvirt }}
  kernel_version_name: ${{ github.event.inputs.kernel_version_name }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Package OpenWrt Firmware
      uses: rin0612/flippy-openwrt-actions@main
      env:
        OPENWRT_ARMVIRT: ${{ env.openwrt_armvirt }}
        SCRIPT_REPO_URL: https://github.com/rin0612/openwrt_packit
        SCRIPT_REPO_BRANCH: master
        KERNEL_REPO_URL: https://github.com/rin0612/openwrt_packit/releases/tag/kernel_stable
        KERNEL_VERSION_NAME: ${{ env.kernel_version_name }}
        KERNEL_AUTO_LATEST: false
        PACKAGE_SOC: s905d
        OPENWRT_VER: R23.11.11
        WHOAMI: 杀生丸大人

    - name: Upload Release
      uses: rin0612/release-action@v1
      with:
        tag: packit.${{ env.PACKAGED_OUTPUTDATE }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ```
          ${{ toJson(env) }}
          ```
