# 推送文件到releases

name: part-push-releases

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: 准备需要推送到releases的文件
      run: |
        echo "----------准备将/opt/2024/*推送到releases--------------"
        mkdir -p /opt/2024
        dd if=/dev/zero of=/opt/2024/tmp.tar.gz bs=1 count=1
        cd /opt/2024
        echo "----------保存推送文件和推送日期信息的到环境变量-------"
        echo "PACKAGED_OUTPUTDATE=$(date +"%Y.%m.%d.%H%M")" >>$GITHUB_ENV
        echo "PACKAGED_OUTPUTPATH=${PWD}" >>$GITHUB_ENV

    - name: 推送文件到releases,tag不存在会创建
      uses: rin0612/release-action@v1
      with:
        tag: ${{ env.PACKAGED_OUTPUTDATE }}_releases的tag
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ### **${{ env.PACKAGED_OUTPUTDATE }}_releases的budy适用于md语法**
