# 推送文件到releases

name: part-push-releases-1

on:
  repository_dispatch:
  workflow_dispatch:

env:
  # TODO 导出配置待处理
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 5.10-lede+kenzok8-max-v3.config
  INIT_CONFIG_SH: init-config.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: 准备需要推送到releases的文件
      run: |
        echo "----------准备将/opt/2024/*推送到releases--------------"
        mkdir -p /opt/2024
        dd if=/dev/zero of=/opt/2024/tmp.tar.gz bs=1 count=1
        cd /opt/2024
        echo "----------保存推送文件和推送日期信息的到环境变量-------"
        echo "PACKAGED_OUTPUTDATE=$(date +"%Y.%m.%d.%H%M")" >>$GITHUB_ENV
        echo "PACKAGED_OUTPUTPATH=${PWD}" >>$GITHUB_ENV

    - name: 推送文件到releases,如果tag不存在会创建
      uses: rin0612/release-action@v1
      with:
        tag: ${{ env.PACKAGED_OUTPUTDATE }}_releases的tag
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          第一行
          ${{ toJson(env) }}
          第三行
