# rootfs.tar.gz和kernel与n1打包脚本制作镜像

name: part-packit-img-2022

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      openwrt_armvirt:
        description: '打包使用的rootfs.tar.gz,链接或者文件目录'
        required: true
        default: https://github.com/sswdr/openwrt-actions/releases/download/backup.2022.04.25_build.2022.04.25.18.00/2022.04.29.1427_5.10-lede+kenzok8-max-v3.config_openwrt-armvirt-64-default-rootfs.tar.gz
      script_repo_url:
        description: '打包仓库地址'
        required: true
        default: https://github.com/rin0612/openwrt_packit
      script_repo_branch:
        description: '打包仓库分支'
        required: true
        default: backup.2022.04.25
      kernel_repo_url:
        description: '打包使用的内核地址,默认是 https://github.com/breakings/OpenWrt/releases/download/kernel_stable'
        required: true
        default: https://github.com/rin0612/openwrt_packit/releases/download/kernel_stable
      kernel_version:
        description: '打包使用的内核版本'
        required: true
        default: 5.10.110
      kernel_version_name:
        description: 'KERNEL_VERSION_NAME用于打包仓库中的make.env的KERNEL_VERSION,用于选择并打包的内核,来自于下载的kernel压缩包中的文件名称'
        required: true
        default: 5.10.110-flippy-71+
      run_sh:
        description: '指定SOC'
        required: true
        default: mk_s905d_n1.sh
      openwrt_ver:
        description: '指定打包仓库中make.env中OPENWRT_VER的值,来自于lede仓库的zzz-default-settings,用于firmware中展示'
        required: true
        default: R22.4.1
      whoami:
        description: '指定打包仓库中make.env中WHOAMI的值,用于firmware中展示'
        required: true
        default: 杀生丸大人
      tag_name:
        description: '指定tag名称,为false则使用新的tag名称'
        required: true
        default: false

env:
  openwrt_armvirt: ${{ github.event.inputs.openwrt_armvirt }}
  script_repo_url: ${{ github.event.inputs.script_repo_url }}
  script_repo_branch: ${{ github.event.inputs.script_repo_branch }}
  kernel_repo_url: ${{ github.event.inputs.kernel_repo_url }}
  kernel_version: ${{ github.event.inputs.kernel_version }}
  kernel_version_name: ${{ github.event.inputs.kernel_version_name }}
  run_sh: ${{ github.event.inputs.run_sh }}
  openwrt_ver: ${{ github.event.inputs.openwrt_ver }}
  whoami: ${{ github.event.inputs.whoami }}
  tag_name: ${{ github.event.inputs.tag_name }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Package OpenWrt Firmware
      uses: rin0612/openwrt_packit@backup.2022.04.25
      env:
        OPENWRT_ARMVIRT: ${{ env.openwrt_armvirt }}
        SCRIPT_REPO_URL: ${{ env.script_repo_url }}
        SCRIPT_REPO_BRANCH: ${{ env.script_repo_branch }}
        KERNEL_REPO_URL: ${{ env.kernel_repo_url }}
        KERNEL_VERSION: ${{ env.kernel_version }}
        KERNEL_VERSION_NAME: ${{ env.kernel_version_name }}
        run_sh: ${{ env.run_sh }}
        OPENWRT_VER: ${{ env.openwrt_ver }}
        WHOAMI: ${{ env.whoami }}

    - name: Prepare Package Env
      run: |
        cd $PACKAGED_OUTPUTPATH
        for file in openwrt_$package_soc_*.img.gz; do
          touch "${file/.img.gz/.env}"
        done
        echo "${{ toJson(env) }}" >> openwrt_$package_soc_*.env
        if [ "$tag_name" == false ]; then
            echo "tag_name=packit.$(date +"%Y.%m.%d.%H.%M")" >> $GITHUB_ENV
        fi

    - name: Upload Release
      uses: rin0612/release-action@v1.14.0
      with:
        tag: ${{ env.tag_name }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/openwrt_${{ env.package_soc }}*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        # omitBody默认值为false,即覆盖原先的正文.true则不更新release的body正文
        omitBody: true
        body: |
          ```
          ${{ toJson(env) }}
          ```
