# 使用releases上次的编译工作目录进行编译
# 目前存在的问题：需要用自己的.config编译，而不是releases中的
name: test-packit

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: '是否ssh连接到actions'
        required: false
        default: true
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 5.10-lede+kenzok8-max-v3.config
  TZ: Asia/Shanghai
  UPLOAD_BIN_DIR: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: 打包内核
      uses: rin0612/openwrt_packit@backup.2022.04.25
      env:
        PACKIT_REPO_URL: https://github.com/rin0612/openwrt_packit
        PACKIT_REPO_BRANCH: backup.2022.04.25
        OPENWRT_ARMVIRT: https://github.com/sswdr/Actions-OpenWrt/releases/download/openwrt_N1_2022.04.29.1427/openwrt-armvirt-64-default-rootfs.tar.gz
        KERNEL_REPO_URL: https://github.com/rin0612/openwrt_packit/releases/download/backup.kernel
        KERNEL_VERSION: 5.10.110
        RUN_SH: mk_s905d_n1.sh
        WHOAMI: 杀生丸大人
        KERNEL_VERSION_NAME: 5.10.110-flippy-71+
        OPENWRT_VER: R22.4.1

    - name: 是否ssh连接到actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

#    - name: 发布固件
#      uses: ncipollo/release-action@v1
#      with:
#        tag: openwrt_N1_${{ env.PACKAGED_OUTPUTDATE }}
#        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
#        allowUpdates: true
#        token: ${{ secrets.GITHUB_TOKEN }}
#        body: |
#          ### **适用于Amlogic平台的N1盒子OpenWrt固件**
#          * **固件信息：**
#          默认IP: `192.168.5.25`
#          默认用户名: `root`
#          默认密码: `password`
