name: Upload Artifacts Example

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Build and generate artifact 1
        run: |
          # Build your project and generate artifact 1
          echo "Building artifact 1..."
          touch artifact1.txt

      - name: Upload artifact 1
        uses: actions/upload-artifact@main
        with:
          name: artifact1
          path: artifact1.txt

      - name: Build and generate artifact 2
        run: |
          # Build your project and generate artifact 2
          echo "Building artifact 2..."
          touch artifact2.txt

      - name: 002
        uses: actions/upload-artifact@main
        with:
          name: 002
          path: artifact2.txt