# 导出编译环境
name: test-workdir-export

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      REPO_URL:
        description: '编译仓库地址[主仓库]'
        required: true
        default: https://github.com/coolsnowwolf/lede
      REPO_BRANCH:
        description: '编译仓库分支[默认主仓库master不需要改]'
        required: true
        default: master
      FEEDS_CONF:
        description: '自定义feeds配置文件[仓库根目录下的文件名称]'
        required: false
        default: feeds.conf.default
      CONFIG_FILE:
        description: '.config配置文件[仓库根目录下build.config/]'
        required: true
        default: build.config/.config
      DIY_P1_SH:
        description: '自定义diy-part1.sh文件名'
        required: true
        default: diy-part1.sh
      DIY_P2_SH:
        description: '自定义diy-part2.sh文件名'
        required: true
        default: diy-part2.sh
      TZ:
        description: '时区配置'
        required: false
        default: Asia/Shanghai
      UPLOAD_BIN_DIR:
        description: '是否上传ipk等bin文件'
        required: false
        default: true

env:
  REPO_URL: ${{ github.event.inputs.REPO_URL }}
  REPO_BRANCH: ${{ github.event.inputs.REPO_BRANCH }}
  FEEDS_CONF: ${{ github.event.inputs.FEEDS_CONF }}
  CONFIG_FILE: ${{ github.event.inputs.CONFIG_FILE }}
  DIY_P1_SH: ${{ github.event.inputs.DIY_P1_SH }}
  DIY_P2_SH: ${{ github.event.inputs.DIY_P2_SH }}
  TZ: ${{ github.event.inputs.TZ }}
  UPLOAD_BIN_DIR: ${{ github.event.inputs.UPLOAD_BIN_DIR }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:


    - name: echo test
      run: |
        echo $REPO_URL
        echo ${{ github.event.inputs.REPO_URL }}

    - name: 编译环境导出：workdir.tar.gz
      uses: ncipollo/release-action@v1
      with:
        tag: dev_${{ github.event.inputs.REPO_URL }}
        artifacts:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          * ${{ github.event.inputs.REPO_URL }} || $REPO_URL


